      SUBROUTINE NCCONC
!	  THIS SUBROUTINE CALCULATES GAS CONCENTRATIONS IN LIQUID AND 
!	  AIR PHASES
      USE PARM
	  DO J=1,NBCL
	      ! CLO2=CONC GAS IN LIQ PHASE (G/M3 WATER)
          CLO2(J)=AO2C(J)/(AFP(J)*HKPO(J)+VWC(J))   
          ! CGO2=CONC GAS IN GAS PHASE (G/M3 AIR)
          CGO2(J)=AO2C(J)/(TPOR(J)+VWC(J)*(1./HKPO(J)-1.))
          ! CLCO2=CONC GAS IN LIQ PHASE
          CLCO2(J)=ACO2C(J)/(AFP(J)*HKPC(J)+VWC(J))   
          ! CGCO2=CONC GAS IN GAS PHASE
          CGCO2(J)=ACO2C(J)/(TPOR(J)+VWC(J)*(1./HKPC(J)-1.))
          ! CLN2O=CONC GAS IN LIQ PHASE
	      CLN2O(J)=AN2OC(J)/(AFP(J)*HKPN(J)+VWC(J)) 
          ! CGN2O=CONC GAS IN GAS PHASE
          CGN2O(J)=AN2OC(J)/(TPOR(J)+VWC(J)*(1./HKPN(J)-1.))
      END DO
      RETURN
      END