      SUBROUTINE NDNITAK
!     EPIC1102
!     THIS SUBPROGRAM DEVELOPED BY ARMEN KEMANIAN ESTIMATES DAILY 
!     DENITRIFICATION AND N2O LOSSES OF SOIL NO3.
	  USE PARM
	  WDN(ISL)=0.
	  DN2O=0.
!     COMPUTE WATER FACTOR
	  AIRV=MAX(0.,(PO(ISL)-ST(ISL))/DZA)
	  X1=0.90+.001*CLA(ISL)
	  X2=(1.0001-AIRV)/X1
	  IF(X2<.8)RETURN
	  H2OF(ISL)=1./(1.+X2**(-60))
!     COMPUTE NITRATE FACTOR
	  ONO3_C=MAX(1.E-5,1000.*WNO3(ISL)/WT(ISL))
 	  WNO3F(ISL)=ONO3_C/(ONO3_C+60.)
!     COMPUTE RESPIRATION FACTOR
	  X3=1000.*RSPC(ISL)/WT(ISL)
	  CBNF(ISL)=MIN(1.,X3/50.)
	  D_F=WNO3F(ISL)*H2OF(ISL)*CBNF(ISL)
	  DNITMX=32.
	  !WDN=MIN(PRMT(30),D_F*DNITMX*WT(ISL)/1000.)
      WDN(ISL)=D_F*DNITMX*WT(ISL)/1000.
	  IF(WDN(ISL)>WNO3(ISL))WDN(ISL)=WNO3(ISL)
	  !compute N2O as a fraction of WDN
	  DN2O=WNO3F(ISL)*(1.-SQRT(H2OF(ISL)))*(1.-CBNF(ISL)**.25)*WDN(ISL)
	  WNO3(ISL)=WNO3(ISL)-WDN(ISL)
      RETURN
	  END