      SUBROUTINE NDNIT
!     EPIC1102
!     THIS SUBPROGRAM ESTIMATES DAILY LOSS OF NO3 BY DENITRIFICATION.
      USE PARM
      AIRV=MAX(0.,(PO(ISL)-ST(ISL))/DZA)
	  X1=0.90+.001*CLA(ISL)
	  X2=(1.0001-AIRV)/X1
	  IF(X2<.8)RETURN
	  F_H2O=1./(1.+X2**(-60))
      !X1=MAX(1.E-5,1000.*WNO3(ISL)/WT(ISL))
 	  !F_NO3=X1/(X1+60.)
      !F=X2/(X2+EXP(SCRP(25,1)-SCRP(25,2)*X2))
	  !X1=MIN(PRMT(4),1.-EXP(-RSPC(ISL)/WT(ISL)))
      F=SQRT(CDG(ISL)*SUT(ISL))*F_H2O
      WDN(ISL)=WNO3(ISL)*F
	  IF(WDN(ISL)>WNO3(ISL))WDN(ISL)=WNO3(ISL)
      WNO3(ISL)=WNO3(ISL)-WDN(ISL)
      DN2=PRMT(80)*WDN(ISL)
      DN2O=WDN(ISL)-DN2
	  RETURN
      END