      SUBROUTINE NRSPC(CS)
!     EPIC1102
!     THIS SUBPROGRAM SIMULATES C RESPIRATION USING EQUATIONS TAKEN 
!     FROM CENTURY.
      USE PARM
      XZ=WNO3(ISL)+WNO2(ISL)+WNH3(ISL)
!     AD1=WLSN(ISL)+WLMN(ISL)+WBMN(ISL)+WHSN(ISL)+WHPN(ISL)+XZ
      RLR=WLSL(ISL)/(WLS(ISL)+1.E-5)
      IF(RLR>.8)THEN
          RLR=.8
      ELSE
          IF(RLR<.1)RLR=.1
      END IF    
	  APCO2=.55
      ASCO2=.60
      IF(ISL==LD1)THEN
          CS=CS*PRMT(51)
          ABCO2=.55
          A1CO2=.55
          RBM=.0164
          RLM=.0405
          RLS=.0107
          HPNC=.1
          XBM=1.
      ELSE
          ABCO2=.17+.0068*SAN(ISL)
          A1CO2=.55
          RBM=.02
          RLM=.0507
          RLS=.0132
          XBM=.25+.0075*SAN(ISL)
          HPNC=WHPN(ISL)/WHPC(ISL) 
      END IF
      BMNC=WBMN(ISL)/WBMC(ISL)
      HSNC=WHSN(ISL)/WHSC(ISL)
      WLMC(ISL)=MAX(.01,WLMC(ISL))
      XLMNC=WLMN(ISL)/WLMC(ISL)
      WLSC(ISL)=MAX(.01,WLSC(ISL))
      XLSNC=WLSN(ISL)/WLSC(ISL)
      ABP=.003+.00032*CLA(ISL)
      ASP=MAX(.001,PRMT(45)-.00009*CLA(ISL))
      A1=1.-A1CO2
      ASX=1.-ASCO2-ASP
      APX=1.-APCO2
      ! TRANSFORMATION STRUCTURAL LITTER WBM 2012-11-22
      ! CR = scaling factor for decomposition (0 - 1) basewd BMNC and &
      ! ratio of NC-substrate/Yield. 
      CRX=1.-(CRUNC-BMNC)/(CRUNC-CRLNC)
      CR=0.
      IF(BMNC>CRLNC.AND.BMNC<CRUNC)CR=CRX
      IF(WLSN(ISL)/(WLSC(ISL)*(1-RLR))/A1>BMNC.OR.BMNC>CRUNC)CR=1.
      X1=RLS*CS*CR*EXP(-3.*RLR)
      X2=1.-RLR
      TLSLNCA=X1*WLSC(ISL)*X2
      TLSLCA=TLSLNCA*RLR/X2
      TLSCA=TLSLNCA/X2
      TLSNA=TLSCA*XLSNC
      ! TRANSFORMATIONS METABOLIC LITTER; SIX LINES BELOW ADDED WBM 2012-11-14
      CR=0.
      IF(BMNC>CRLNC.AND.BMNC<CRUNC)CR=CRX
      IF(XLMNC/A1>BMNC.OR.BMNC>CRUNC)CR=1.
      X1=RLM*CS*CR
      TLMCA=WLMC(ISL)*X1
      TLMNA=TLMCA*XLMNC
      ! TRANSFORMATIONS MICROBIAL BIOMASS; NEXT SIX LINES ADDED WBM 2012-11-22
      CR=0.
      IF(BMNC>CRLNC.AND.BMNC<CRUNC)CR=CRX
      IF(BMNC/(1.-ABCO2)>BMNC.OR.BMNC>CRUNC)CR=1.
      TBMCA=WBMC(ISL)*RBM*CS*CR*XBM
      TBMNA=TBMCA*BMNC
      ! TRANSFORMATION OF SLOW HUMUS; NEXT SIX LINES ADDED WBM 2012-11-22
      CR=0.
      IF(BMNC>CRLNC.AND.BMNC<CRUNC)CR=CRX
      IF(HSNC/(1.-ASCO2)>BMNC.OR.BMNC>CRUNC)CR=1.
      THSCA=WHSC(ISL)*RHS*CS*CR
      THSNA=THSCA*HSNC
      ! TRANSFORMATIONS OF PASSIVE HUMUS; NEXT SIX LINES ADDED WBM 2012-11-22
      CR=0.
      IF(BMNC>CRLNC.AND.BMNC<CRUNC)CR=CRX
      IF(HPNC/APX>BMNC.OR.BMNC>CRUNC)CR=1.
      THPCA=WHPC(ISL)*CS*CR*RHP
      THPNA=THPCA*HPNC
      IF(ISL==LD1) THEN
          RSPC(ISL)=MAX(0.,.3*TLSLCA+A1CO2*(TLSLNCA+TLMCA)+ABCO2*TBMCA+&
          ASCO2*THSCA)
      ELSE
          RSPC(ISL)=MAX(0.,.3*TLSLCA+A1CO2*(TLSLNCA+TLMCA)+ABCO2*TBMCA+&
          ASCO2*THSCA+APCO2*THPCA)
      END IF    
      RETURN
      END